name: Metrics (Isometric Calendar)

on:
  schedule: [{ cron: "0 0 * * 1" }]  # Roda toda segunda
  workflow_dispatch:                # Permite rodar manualmente

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.isocalendar.fullyear.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
